CREATE TABLE "barbers" (
  "barber_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar UNIQUE,
  "phone" varchar,
  "hire_date" date
);

CREATE TABLE "clients" (
  "client_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar,
  "last_name" varchar,
  "email" varchar UNIQUE,
  "phone" varchar,
  "join_date" date
);

CREATE TABLE "services" (
  "service_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text,
  "duration" integer,
  "price" money
);

CREATE TABLE "appointments" (
  "appointment_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "barber_id" integer,
  "client_id" integer,
  "service_id" integer,
  "appointment_date" date,
  "start_time" time,
  "end_time" time,
  "status" varchar
);

CREATE TABLE "barber_services" (
  "barber_id" integer,
  "service_id" integer,
  PRIMARY KEY ("barber_id", "service_id")
);

ALTER TABLE "appointments" ADD FOREIGN KEY ("barber_id") REFERENCES "barbers" ("barber_id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("client_id") REFERENCES "clients" ("client_id");

ALTER TABLE "appointments" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("service_id");

ALTER TABLE "barber_services" ADD FOREIGN KEY ("barber_id") REFERENCES "barbers" ("barber_id");

ALTER TABLE "barber_services" ADD FOREIGN KEY ("service_id") REFERENCES "services" ("service_id");
